dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
cache:
  - pip

install:
  - pip install -r requirements.txt

script:
  - python3 generate_chain.py --output-dir=.output
  - cd test && pytest
