dist: xenial
sudo: required
language: python
python:
  - "3.6"
  - "3.7"
cache:
  pip: true

before_install:
  - git clone https://github.com/bitcoin-core/secp256k1.git
  - sudo apt-add-repository ppa:bitcoin/bitcoin -y
  - sudo apt-get update
  - mkdir bin
  - wget https://download.bitcoinabc.org/0.18.5/linux/bitcoin-abc-0.18.5-x86_64-linux-gnu.tar.gz
  - tar -xzvf bitcoin-abc-0.18.5-x86_64-linux-gnu.tar.gz
  - mv ./bitcoin-abc-0.18.5-x86_64-linux-gnu/bitcoind ./bin/bitcoin-cash

install:
  - sudo apt-get install build-essential automake pkg-config libtool libgmp-dev bitcoind -y
  - pip install -r requirements.txt
  - cd secp256k1
  - ./autogen.sh
  - ./configure
  - make -j 2
  - sudo make install
  - cd ..
  - LD_LIBRARY_PATH=/usr/local/lib
  - export LD_LIBRARY_PATH

script:
  - python generate_chain.py --output-dir=.output --chain=btc
  - python generate_chain.py --output-dir=.output --chain=bch --exec=./bin/bitcoin-cash
  - cd tests && pytest

