dist: xenial
sudo: required
language: python
python:
  - "3.6"
  - "3.7"
cache:
  pip: true

addons:
  apt:
    packages:
      - build-essential
      - automake
      - pkg-config
      - libtool
      - libgmp-dev

before_install:
  - git clone https://github.com/bitcoin-core/secp256k1.git

install:
  - pip install -r requirements.txt
  - cd secp256k1
  - ./autogen.sh
  - ./configure
  - make -j 2
  - ./tests
  - sudo make install
  - cd ..
  - LD_LIBRARY_PATH=/usr/local/lib
  - export LD_LIBRARY_PATH

script:
  - python generate_chain.py --output-dir=.output
  - cd test && pytest
